import { Router } from "express";
import { z } from "zod";
import { prisma } from "../config/prisma.js";
import { requireAuth } from "../middleware/auth.js";
import { requireProjectEditor, requireProjectMember } from "../middleware/access.js";
import { logActivity } from "../services/activity.js";
import type { AuthRequest } from "../types.js";

export const commentsRouter = Router();
commentsRouter.use(requireAuth);
commentsRouter.get("/task/:taskId", async (req: AuthRequest, res) => { const task = await prisma.task.findUniqueOrThrow({ where: { id: String(req.params.taskId) } }); await requireProjectMember(task.projectId, req.user!.id); const comments = await prisma.comment.findMany({ where: { taskId: task.id }, include: { author: { select: { id: true, displayName: true, username: true, avatarUrl: true } }, attachments: true, reactions: { include: { user: { select: { id: true, displayName: true, username: true } } } } }, orderBy: { createdAt: "asc" } }); res.json({ comments }); });
commentsRouter.post("/", async (req: AuthRequest, res) => { const input = z.object({ taskId: z.string(), parentId: z.string().nullable().optional(), body: z.string().min(1).max(10000) }).parse(req.body); const task = await prisma.task.findUniqueOrThrow({ where: { id: input.taskId } }); await requireProjectEditor(task.projectId, req.user!.id); const comment = await prisma.comment.create({ data: { ...input, authorId: req.user!.id }, include: { author: { select: { id: true, displayName: true, username: true, avatarUrl: true } } } }); await logActivity({ projectId: task.projectId, taskId: task.id, userId: req.user!.id, action: input.parentId ? "COMMENT_REPLIED" : "COMMENT_CREATED" }); req.app.get("io").to(`project:${task.projectId}`).emit("comment:created", comment); res.status(201).json({ comment }); });
commentsRouter.post("/:commentId/reactions", async (req: AuthRequest, res) => { const { emoji } = z.object({ emoji: z.string().min(1).max(12) }).parse(req.body); const existing = await prisma.comment.findUniqueOrThrow({ where: { id: String(req.params.commentId) }, include: { task: true } }); await requireProjectMember(existing.task.projectId, req.user!.id); const key = { commentId_userId_emoji: { commentId: existing.id, userId: req.user!.id, emoji } }; const reaction = await prisma.commentReaction.findUnique({ where: key }); if (reaction) await prisma.commentReaction.delete({ where: key }); else await prisma.commentReaction.create({ data: { commentId: existing.id, userId: req.user!.id, emoji } }); req.app.get("io").to(`project:${existing.task.projectId}`).emit("comment:reaction", { commentId: existing.id, userId: req.user!.id, emoji, active: !reaction }); res.json({ active: !reaction }); });
commentsRouter.patch("/:commentId", async (req: AuthRequest, res) => { const body = z.object({ body: z.string().min(1).max(10000) }).parse(req.body); const existing = await prisma.comment.findUniqueOrThrow({ where: { id: String(req.params.commentId) }, include: { task: true } }); const member = await requireProjectMember(existing.task.projectId, req.user!.id); if (existing.authorId !== req.user!.id && member.role !== "OWNER") return res.status(403).json({ error: "Only the comment author or project owner can edit this comment" }); const comment = await prisma.comment.update({ where: { id: existing.id }, data: body }); await logActivity({ projectId: existing.task.projectId, taskId: existing.taskId, userId: req.user!.id, action: "COMMENT_UPDATED" }); req.app.get("io").to(`project:${existing.task.projectId}`).emit("comment:updated", comment); res.json({ comment }); });
commentsRouter.delete("/:commentId", async (req: AuthRequest, res) => { const existing = await prisma.comment.findUniqueOrThrow({ where: { id: String(req.params.commentId) }, include: { task: true } }); const member = await requireProjectMember(existing.task.projectId, req.user!.id); if (existing.authorId !== req.user!.id && member.role !== "OWNER") return res.status(403).json({ error: "Only the comment author or project owner can delete this comment" }); const comment = await prisma.comment.update({ where: { id: existing.id }, data: { body: "[deleted]", deletedAt: new Date() } }); await logActivity({ projectId: existing.task.projectId, taskId: existing.taskId, userId: req.user!.id, action: "COMMENT_DELETED" }); req.app.get("io").to(`project:${existing.task.projectId}`).emit("comment:deleted", { commentId: comment.id }); res.json({ ok: true }); });
