import { Router } from "express";
import { z } from "zod";
import { prisma } from "../config/prisma.js";
import { requireAuth } from "../middleware/auth.js";
import { requireProjectEditor, requireProjectMember } from "../middleware/access.js";
import { logActivity } from "../services/activity.js";
import type { AuthRequest } from "../types.js";

export const tasksRouter = Router();
tasksRouter.use(requireAuth);
const taskInput = z.object({ projectId: z.string(), parentId: z.string().nullable().optional(), title: z.string().min(1).max(300), description: z.string().max(10000).default(""), status: z.enum(["TODO","IN_PROGRESS","BLOCKED","REVIEW","TESTING","DONE","CLOSED","CANCELLED"]).default("TODO"), priority: z.enum(["URGENT","HIGH","MEDIUM","LOW"]).default("MEDIUM"), assigneeId: z.string().nullable().optional(), startDate: z.coerce.date().nullable().optional(), dueDate: z.coerce.date().nullable().optional(), estimatedMinutes: z.number().int().positive().nullable().optional(), position: z.number().default(0) });
tasksRouter.get("/project/:projectId", async (req: AuthRequest, res) => { await requireProjectMember(req.params.projectId, req.user!.id); const tasks = await prisma.task.findMany({ where: { projectId: req.params.projectId, deletedAt: null }, include: { assignee: { select: { id: true, displayName: true, username: true } }, _count: { select: { comments: true, children: true, attachments: true } } }, orderBy: [{ parentId: "asc" }, { position: "asc" }, { createdAt: "desc" }] }); res.json({ tasks }); });
tasksRouter.post("/", async (req: AuthRequest, res) => { const input = taskInput.parse(req.body); await requireProjectEditor(input.projectId, req.user!.id); if (input.assigneeId) { const member = await prisma.projectMember.findFirst({ where: { projectId: input.projectId, userId: input.assigneeId, leftAt: null } }); if (!member) return res.status(400).json({ error: "Assignee must be an active project member" }); } const task = await prisma.task.create({ data: { ...input, createdById: req.user!.id, updatedById: req.user!.id } }); await logActivity({ projectId: input.projectId, taskId: task.id, userId: req.user!.id, action: input.parentId ? "SUBTASK_CREATED" : "TASK_CREATED", newValue: { title: task.title } }); req.app.get("io").to(`project:${input.projectId}`).emit("task:created", task); res.status(201).json({ task }); });
tasksRouter.patch("/:taskId", async (req: AuthRequest, res) => { const existing = await prisma.task.findUniqueOrThrow({ where: { id: req.params.taskId } }); await requireProjectEditor(existing.projectId, req.user!.id); const patch = taskInput.omit({ projectId: true }).partial().parse(req.body); if (patch.assigneeId) { const member = await prisma.projectMember.findFirst({ where: { projectId: existing.projectId, userId: patch.assigneeId, leftAt: null } }); if (!member) return res.status(400).json({ error: "Assignee must be an active project member" }); } const task = await prisma.task.update({ where: { id: existing.id }, data: { ...patch, updatedById: req.user!.id } }); await logActivity({ projectId: existing.projectId, taskId: task.id, userId: req.user!.id, action: "TASK_UPDATED", oldValue: existing, newValue: task }); req.app.get("io").to(`project:${existing.projectId}`).emit("task:updated", task); res.json({ task }); });
tasksRouter.delete("/:taskId", async (req: AuthRequest, res) => { const existing = await prisma.task.findUniqueOrThrow({ where: { id: req.params.taskId } }); await requireProjectEditor(existing.projectId, req.user!.id); const task = await prisma.task.update({ where: { id: existing.id }, data: { deletedAt: new Date(), updatedById: req.user!.id } }); await logActivity({ projectId: existing.projectId, taskId: task.id, userId: req.user!.id, action: "TASK_DELETED" }); req.app.get("io").to(`project:${existing.projectId}`).emit("task:deleted", { taskId: task.id }); res.json({ ok: true }); });
tasksRouter.post("/:taskId/restore", async (req: AuthRequest, res) => { const existing = await prisma.task.findUniqueOrThrow({ where: { id: req.params.taskId } }); await requireProjectEditor(existing.projectId, req.user!.id); const task = await prisma.task.update({ where: { id: existing.id }, data: { deletedAt: null, updatedById: req.user!.id } }); await logActivity({ projectId: existing.projectId, taskId: task.id, userId: req.user!.id, action: "TASK_RESTORED" }); req.app.get("io").to(`project:${existing.projectId}`).emit("task:restored", task); res.json({ task }); });
